# Generated by Django 5.2.11 on 2026-02-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_role_customuser_is_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
