# Generated by Django 5.2.11 on 2026-02-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSP', '0002_documentapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
