# Generated by Django 5.2.11 on 2026-02-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSP', '0003_alter_documentapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentapplication',
            name='has_seen',
            field=models.BooleanField(default=False),
        ),
    ]
