# Generated by Django 5.2.11 on 2026-02-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSP', '0007_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
