# Generated by Django 5.2.11 on 2026-02-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSP', '0008_alter_profile_prof_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentapplication',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
