# Generated by Django 5.2.11 on 2026-02-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSP', '0009_documentapplication_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentapplication',
            name='is_published',
        ),
    ]
