# Generated by Django 5.2.11 on 2026-06-16 07:35

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSP', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentapplication',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='documentapplication',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
