# Generated by Django 5.2.11 on 2026-06-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSP', '0012_documentapplication_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentapplication',
            name='date',
        ),
        migrations.AlterField(
            model_name='documentapplication',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
